services:
  iiahrcrew_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iiahrcrew_container
    restart: always
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - ./google_credentials.json:/app/google_credentials.json
    networks:
      - internal_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      # Router Configuration
      - "traefik.http.routers.iiahrcrew.rule=Host(`iiahrcrew.aiwithbala.in`)"
      - "traefik.http.routers.iiahrcrew.entrypoints=websecure"
      - "traefik.http.routers.iiahrcrew.tls.certresolver=letsencrypt"
      # Service Configuration (Routing to Port 8502)
      - "traefik.http.services.iiahrcrew.loadbalancer.server.port=8502"

networks:
  internal_net:
    driver: bridge
  traefik_net:
    external: true
    name: n8n-pkrc_default